apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nginx
    monitoring: 'true'
  name: myds
  namespace: batch1
spec:
  selector:
    matchLabels:
      app: nginx
      monitoring: 'true'
  template:
    metadata:
      labels:
        app: nginx
        monitoring: 'true'
    spec:
        nodeSelector:
          dev: 'kishore'
        containers:
          - name: nginx
            image: 'nginx:1.10.0'