apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
  namespace: batch1
spec:
  storageClassName: azurefile-csi 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi